x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "qwertyuiop1234567890"'
    ]
    volumes:
      - redis-data:/data
    <<: *default-logging
    ports:
      - "6379"
    restart: always

volumes:
  redis-data:
